export enum MessageType {
  CompleteResponse = 0,

  StreamOutput = 1,
  StreamError = 2,
  StreamEnd = 3,

  CommandKill = 4,
  CommandKillResult = 5,
  CommandExecute = 6,

  PasswordRequest = 7,
  PasswordProvide = 8,
  SessionCreate = 10,
  SessionSetActive = 11,
  SessionLoad = 12,
  SessionList = 13,
  SessionDelete = 14,
  SessionUpdateTargets = 15,
  SessionUpdate = 16,
  SessionAddTarget = 17,
  SessionDeleteTarget = 18,
  SessionEditTarget = 19,
  SessionCreateResult = 20,
  SessionSetActiveResult = 21,
  SessionLoadResult = 22,
  SessionListResult = 23,
  SessionDeleteResult = 24,
  SessionUpdateResult = 25,
  SessionAddTargetResult = 26,
  SessionDeleteTargetResult = 27,
  SessionEditTargetResult = 28,
  SessionOperationError = 29,

  CustomScriptCreate = 30,
  CustomScriptUpdate = 31,
  CustomScriptDelete = 32,
  CustomScriptList = 33,
  CustomScriptCreateResult = 40,
  CustomScriptUpdateResult = 41,
  CustomScriptDeleteResult = 42,
  CustomScriptListResult = 43,
  CustomScriptOperationError = 49,

  WriteUpCreate = 50,
  WriteUpUpdate = 51,
  WriteUpDelete = 52,
  WriteUpList = 53,
  WriteUpLoad = 54,
  WriteUpMove = 55,
  WriteUpCreateResult = 60,
  WriteUpUpdateResult = 61,
  WriteUpDeleteResult = 62,
  WriteUpListResult = 63,
  WriteUpLoadResult = 64,
  WriteUpMoveResult = 65,
  WriteUpOperationError = 69,

  MediaUpload = 70,
  MediaLoad = 71,
  MediaDelete = 72,
  MediaList = 73,
  MediaUploadResult = 80,
  MediaLoadResult = 81,
  MediaDeleteResult = 82,
  MediaListResult = 83,
  MediaOperationError = 89,

  ProjectCreate = 90,
  ProjectLoad = 91,
  ProjectList = 92,
  ProjectUpdate = 93,
  ProjectDelete = 94,
  ProjectAddFolder = 95,
  ProjectDeleteFolder = 96,
  ProjectRenameFolder = 97,
  ProjectAssignSession = 98,
  ProjectCreateResult = 100,
  ProjectLoadResult = 101,
  ProjectListResult = 102,
  ProjectUpdateResult = 103,
  ProjectDeleteResult = 104,
  ProjectAddFolderResult = 105,
  ProjectDeleteFolderResult = 106,
  ProjectRenameFolderResult = 107,
  ProjectAssignSessionResult = 108,
  ProjectOperationError = 109,
  ProjectListSessions = 110,
  ProjectListSessionsResult = 111,
  ProjectListWriteUps = 112,
  ProjectListWriteUpsResult = 113,

  ToolInventoryRequest = 120,
  ToolInventoryResult = 121,
  ToolInstallRequest = 122,
  ToolInstallAccepted = 123,
  ToolInstallProgress = 124,
  ToolOperationError = 125,
  ToolCatalogSnapshot = 126,
}
