export enum MessageType {
  CompleteResponse = 0,
  StreamOutput = 1,
  StreamError = 2,
  StreamEnd = 3,
  CommandKill = 4,
  CommandKillResult = 5,
  CommandExecute = 6,
  PasswordRequest = 7,
  PasswordProvide = 8,
  CommandSignal = 9,
  CommandInput = 150,

  SessionCreate = 10,
  SessionSetActive = 11,
  SessionLoad = 12,
  SessionList = 13,
  SessionDelete = 14,
  SessionUpdateTargets = 15,
  SessionUpdate = 16,
  SessionAddTarget = 17,
  SessionDeleteTarget = 18,
  SessionEditTarget = 19,

  SessionCreateResult = 20,
  SessionSetActiveResult = 21,
  SessionLoadResult = 22,
  SessionListResult = 23,
  SessionDeleteResult = 24,
  SessionUpdateResult = 25,
  SessionAddTargetResult = 26,
  SessionDeleteTargetResult = 27,
  SessionEditTargetResult = 28,
  SessionOperationError = 29,

  CustomScriptCreate = 30,
  CustomScriptUpdate = 31,
  CustomScriptDelete = 32,
  CustomScriptList = 33,

  CustomScriptCreateResult = 40,
  CustomScriptUpdateResult = 41,
  CustomScriptDeleteResult = 42,
  CustomScriptListResult = 43,
  CustomScriptOperationError = 49,

  WriteUpCreate = 50,
  WriteUpUpdate = 51,
  WriteUpDelete = 52,
  WriteUpList = 53,
  WriteUpLoad = 54,
  WriteUpMove = 55,

  WriteUpCreateResult = 60,
  WriteUpUpdateResult = 61,
  WriteUpDeleteResult = 62,
  WriteUpListResult = 63,
  WriteUpLoadResult = 64,
  WriteUpMoveResult = 65,
  WriteUpOperationError = 69,

  MediaUpload = 70,
  MediaLoad = 71,
  MediaDelete = 72,
  MediaList = 73,

  MediaUploadResult = 80,
  MediaLoadResult = 81,
  MediaDeleteResult = 82,
  MediaListResult = 83,
  MediaOperationError = 89,

  ProjectCreate = 90,
  ProjectLoad = 91,
  ProjectList = 92,
  ProjectUpdate = 93,
  ProjectDelete = 94,
  ProjectAddFolder = 95,
  ProjectDeleteFolder = 96,
  ProjectRenameFolder = 97,
  ProjectAssignSession = 98,

  ProjectCreateResult = 100,
  ProjectLoadResult = 101,
  ProjectListResult = 102,
  ProjectUpdateResult = 103,
  ProjectDeleteResult = 104,
  ProjectAddFolderResult = 105,
  ProjectDeleteFolderResult = 106,
  ProjectRenameFolderResult = 107,
  ProjectAssignSessionResult = 108,
  ProjectOperationError = 111,

  ProjectListSessions = 110,
  ProjectListWriteUps = 112,

  ProjectListSessionsResult = 109,
  ProjectListWriteUpsResult = 113,

  ProjectExport = 114,
  ProjectExportResult = 115,
  ProjectImport = 116,
  ProjectImportResult = 117,
  ProjectListExports = 118,
  ProjectListExportsResult = 119,

  ToolInventoryRequest = 120,
  ToolInstallRequest = 121,

  ToolInventoryResult = 130,
  ToolInstallAccepted = 131,
  ToolInstallProgress = 132,
  ToolOperationError = 139,
  ToolCatalogSnapshot = 140,
}
