export enum ToolCategory {
  PORT_SCANNING = 'PORT_SCANNING',
  WEB_DISCOVERY = 'WEB_DISCOVERY',
  WEB_VULN_SCAN = 'WEB_VULN_SCAN',
  REVERSE_SHELL = 'REVERSE_SHELL',
  EXPLOIT = 'EXPLOIT',
  OTHER = 'OTHER',
}
